// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDw1-t61wHO0tbbijkdndNgW-fNAucWYN0',
    appId: '1:815346536690:web:96ce5f8c0b532f62cf406b',
    messagingSenderId: '815346536690',
    projectId: 'myfirstmainproject',
    authDomain: 'myfirstmainproject.firebaseapp.com',
    storageBucket: 'myfirstmainproject.appspot.com',
    measurementId: 'G-FECCQEJHQN',
      databaseURL: 'https://myfirstmainproject-default-rtdb.firebaseio.com/'
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSBRjgTKdDwui_r82lpcKOjYCQ4LhO-Bk',
    appId: '1:815346536690:android:9934e379d8f11670cf406b',
    messagingSenderId: '815346536690',
    projectId: 'myfirstmainproject',
    storageBucket: 'myfirstmainproject.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNRzilrefz5D8Ssoxf-iE7lHzi3H-IYUY',
    appId: '1:815346536690:ios:9f2e0df9efca4c56cf406b',
    messagingSenderId: '815346536690',
    projectId: 'myfirstmainproject',
    storageBucket: 'myfirstmainproject.appspot.com',
    iosBundleId: 'com.example.myfirstmainproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNRzilrefz5D8Ssoxf-iE7lHzi3H-IYUY',
    appId: '1:815346536690:ios:9f2e0df9efca4c56cf406b',
    messagingSenderId: '815346536690',
    projectId: 'myfirstmainproject',
    storageBucket: 'myfirstmainproject.appspot.com',
    iosBundleId: 'com.example.myfirstmainproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDw1-t61wHO0tbbijkdndNgW-fNAucWYN0',
    appId: '1:815346536690:web:c691d932b40f10a6cf406b',
    messagingSenderId: '815346536690',
    projectId: 'myfirstmainproject',
    authDomain: 'myfirstmainproject.firebaseapp.com',
    storageBucket: 'myfirstmainproject.appspot.com',
    measurementId: 'G-6FE9L1MLW8',
  );
}
